/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MyTradesRouteImport } from './routes/my-trades'
import { Route as CreateOfferRouteImport } from './routes/create-offer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeIdRouteImport } from './routes/trade.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTradesRoute = MyTradesRouteImport.update({
  id: '/my-trades',
  path: '/my-trades',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOfferRoute = CreateOfferRouteImport.update({
  id: '/create-offer',
  path: '/create-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeIdRoute = TradeIdRouteImport.update({
  id: '/trade/$id',
  path: '/trade/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-offer': typeof CreateOfferRoute
  '/my-trades': typeof MyTradesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade/$id': typeof TradeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-offer': typeof CreateOfferRoute
  '/my-trades': typeof MyTradesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade/$id': typeof TradeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-offer': typeof CreateOfferRoute
  '/my-trades': typeof MyTradesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade/$id': typeof TradeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-offer'
    | '/my-trades'
    | '/sitemap.xml'
    | '/trade/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-offer' | '/my-trades' | '/sitemap.xml' | '/trade/$id'
  id:
    | '__root__'
    | '/'
    | '/create-offer'
    | '/my-trades'
    | '/sitemap.xml'
    | '/trade/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateOfferRoute: typeof CreateOfferRoute
  MyTradesRoute: typeof MyTradesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradeIdRoute: typeof TradeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trades': {
      id: '/my-trades'
      path: '/my-trades'
      fullPath: '/my-trades'
      preLoaderRoute: typeof MyTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-offer': {
      id: '/create-offer'
      path: '/create-offer'
      fullPath: '/create-offer'
      preLoaderRoute: typeof CreateOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$id': {
      id: '/trade/$id'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof TradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateOfferRoute: CreateOfferRoute,
  MyTradesRoute: MyTradesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradeIdRoute: TradeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
